name: Allow Only Dev to Merge into Main

on:
  pull_request:
    branches:
      - main  # Trigger only if PR targets the 'main' branch

jobs:
  check-branch-source:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch is dev
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ Only 'dev' branch is allowed to merge into 'main'."
            exit 1
          fi
